# Generated by Django 4.0.2 on 2022-02-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('priorty', models.CharField(choices=[('ON', 'One'), ('TW', 'Two'), ('TH', 'Three')], default='ON', max_length=2)),
            ],
        ),
    ]
